# fly.toml app configuration file generated for hi-events-frontend on 2025-01-26T10:17:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hi-events-frontend'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
