<?php

return [
    'deprecated' => [
        'Asia/Calcutta' => 'Asia/Kolkata',
        'Asia/Saigon' => 'Asia/Ho_Chi_Minh',
        'America/Buenos_Aires' => 'America/Argentina/Buenos_Aires',
        'Europe/Kiev' => 'Europe/Kyiv',
        'Africa/Asmera' => 'Africa/Asmara',
        'America/Indianapolis' => 'America/Indiana/Indianapolis',
        'Asia/Chongqing' => 'Asia/Shanghai',
        'Asia/Macao' => 'Asia/Macau',
        'Pacific/Samoa' => 'Pacific/Pago_Pago',
        'Pacific/Yap' => 'Pacific/Chuuk',
        'Etc/Greenwich' => 'Etc/GMT',

        'Etc/GMT+1' => 'Atlantic/Azores',      // UTC-1
        'Etc/GMT+2' => 'Atlantic/South_Georgia', // UTC-2
        'Etc/GMT+3' => 'America/Argentina/Buenos_Aires', // UTC-3
        'Etc/GMT+4' => 'America/La_Paz',     // UTC-4
        'Etc/GMT+5' => 'America/New_York',     // UTC-5
        'Etc/GMT+6' => 'America/Chicago',      // UTC-6
        'Etc/GMT+7' => 'America/Denver',       // UTC-7
        'Etc/GMT+8' => 'America/Los_Angeles',  // UTC-8
        'Etc/GMT+9' => 'America/Anchorage',    // UTC-9
        'Etc/GMT+10' => 'Pacific/Honolulu',    // UTC-10
        'Etc/GMT+11' => 'Pacific/Pago_Pago',   // UTC-11
        'Etc/GMT-1' => 'Europe/Paris',         // UTC+1
        'Etc/GMT-2' => 'Europe/Athens',        // UTC+2
        'Etc/GMT-3' => 'Europe/Moscow',        // UTC+3
        'Etc/GMT-4' => 'Asia/Dubai',           // UTC+4
        'Etc/GMT-5' => 'Asia/Karachi',         // UTC+5
        'Etc/GMT-6' => 'Asia/Dhaka',           // UTC+6
        'Etc/GMT-7' => 'Asia/Bangkok',         // UTC+7
        'Etc/GMT-8' => 'Asia/Singapore',       // UTC+8
        'Etc/GMT-9' => 'Asia/Tokyo',           // UTC+9
        'Etc/GMT-10' => 'Pacific/Port_Moresby',    // UTC+10
        'Etc/GMT-11' => 'Pacific/Noumea',      // UTC+11
        'Etc/GMT-12' => 'Pacific/Fiji',        // UTC+12

        'Africa/Timbuktu' => 'Africa/Bamako',
        'America/Argentina/ComodRivadavia' => 'America/Argentina/Catamarca',
        'America/Atka' => 'America/Adak',
        'America/Ensenada' => 'America/Tijuana',
        'America/Fort_Wayne' => 'America/Indiana/Indianapolis',
        'America/Knox_IN' => 'America/Indiana/Knox',
        'America/Louisville' => 'America/Kentucky/Louisville',
        'America/Montreal' => 'America/Toronto',
        'America/Shiprock' => 'America/Denver',
        'Asia/Ashkhabad' => 'Asia/Ashgabat',
        'Asia/Chungking' => 'Asia/Shanghai',
        'Asia/Dacca' => 'Asia/Dhaka',
        'Asia/Harbin' => 'Asia/Shanghai',
        'Asia/Istanbul' => 'Europe/Istanbul',
        'Asia/Kashgar' => 'Asia/Urumqi',
        'Asia/Tel_Aviv' => 'Asia/Jerusalem',
        'Australia/ACT' => 'Australia/Sydney',
        'Australia/Canberra' => 'Australia/Sydney',
        'Australia/LHI' => 'Australia/Lord_Howe',
        'Australia/NSW' => 'Australia/Sydney',
        'Australia/North' => 'Australia/Darwin',
        'Australia/Queensland' => 'Australia/Brisbane',
        'Australia/South' => 'Australia/Adelaide',
        'Australia/Tasmania' => 'Australia/Hobart',
        'Australia/Victoria' => 'Australia/Melbourne',
        'Australia/West' => 'Australia/Perth',
        'Australia/Yancowinna' => 'Australia/Broken_Hill',
        'Brazil/Acre' => 'America/Rio_Branco',
        'Brazil/DeNoronha' => 'America/Noronha',
        'Brazil/East' => 'America/Sao_Paulo',
        'Brazil/West' => 'America/Manaus',
        'Canada/Atlantic' => 'America/Halifax',
        'Canada/Central' => 'America/Winnipeg',
        'Canada/Eastern' => 'America/Toronto',
        'Canada/Mountain' => 'America/Edmonton',
        'Canada/Newfoundland' => 'America/St_Johns',
        'Canada/Pacific' => 'America/Vancouver',
        'Canada/Saskatchewan' => 'America/Regina',
        'Canada/Yukon' => 'America/Whitehorse',
        'Chile/Continental' => 'America/Santiago',
        'Chile/EasterIsland' => 'Pacific/Easter',
        'Cuba' => 'America/Havana',
        'Egypt' => 'Africa/Cairo',
        'Eire' => 'Europe/Dublin',
        'GB' => 'Europe/London',
        'GB-Eire' => 'Europe/London',
        'Hongkong' => 'Asia/Hong_Kong',
        'Iceland' => 'Atlantic/Reykjavik',
        'Iran' => 'Asia/Tehran',
        'Israel' => 'Asia/Jerusalem',
        'Jamaica' => 'America/Jamaica',
        'Japan' => 'Asia/Tokyo',
        'Kwajalein' => 'Pacific/Kwajalein',
        'Libya' => 'Africa/Tripoli',
        'Mexico/BajaNorte' => 'America/Tijuana',
    ],
];
