services:
  all-in-one:
    build:
      context: ./../../
      dockerfile: Dockerfile.all-in-one
    restart: always
    ports:
      - "172.18.0.1:13336:80"
    environment:
      - VITE_FRONTEND_URL=https://${DOMAIN}
      - VITE_API_URL_CLIENT=https://${DOMAIN}/api
      - VITE_API_URL_SERVER=http://localhost:80/api
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - LOG_CHANNEL=stderr
      - QUEUE_CONNECTION=sync
      - APP_KEY=${APP_KEY}
      - APP_CDN_URL=https://${DOMAIN}/storage
      - APP_FRONTEND_URL=https://${DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
      - APP_DISABLE_REGISTRATION=${APP_DISABLE_REGISTRATION}
      - APP_EMAIL_LOGO_URL=${APP_EMAIL_LOGO_URL}
      - APP_EMAIL_LOGO_LINK_URL=${APP_EMAIL_LOGO_LINK_URL}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - FILESYSTEM_PUBLIC_DISK=public
      - FILESYSTEM_PRIVATE_DISK=local
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    depends_on:
      - postgres

  postgres:
    image: elestio/postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 172.18.0.1:43360:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.18.0.1:31829:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
