[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:frankenphp]
command=php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=auto --caddyfile=/etc/caddy/Caddyfile
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:laravel-queue-worker]
command=php artisan queue:work --queue=default,webhook-queue --sleep=3 --tries=3 --timeout=60
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
