FROM serversideup/php:8.4-fpm-nginx-alpine

ENV PHP_OPCACHE_ENABLE=1
ENV NGINX_WEBROOT=/var/www/html/public

WORKDIR /var/www/html

RUN mkdir -p /var/www/html/storage /var/www/html/bootstrap/cache \
    && chown -R www-data:www-data /var/www/html

COPY --chown=www-data:www-data . /var/www/html

# Switch to root user to install PHP extensions
USER root
RUN install-php-extensions intl
USER www-data

RUN chmod -R 755 /var/www/html/storage \
    && chmod -R 775 /var/www/html/bootstrap/cache
