<?php

namespace HiEvents\DomainObjects\Enums;

enum OrderAuditAction: string
{
    use BaseEnum;

    case ATTENDEE_UPDATED = 'ATTENDEE_UPDATED';
    case ORDER_UPDATED = 'ORDER_UPDATED';
    case ATTENDEE_EMAIL_RESENT = 'ATTENDEE_EMAIL_RESENT';
    case ORDER_EMAIL_RESENT = 'ORDER_EMAIL_RESENT';
    case AUTOMATIC_REFUND_SKIPPED = 'AUTOMATIC_REFUND_SKIPPED';
    case AUTOMATIC_REFUND_FAILED = 'AUTOMATIC_REFUND_FAILED';
    case MANUAL_ATTENDEE_CAPACITY_OVERRIDE = 'MANUAL_ATTENDEE_CAPACITY_OVERRIDE';
    case BOX_OFFICE_PRICE_ADJUSTED = 'BOX_OFFICE_PRICE_ADJUSTED';
    case BOX_OFFICE_ORDER_VOIDED = 'BOX_OFFICE_ORDER_VOIDED';
    case BOX_OFFICE_EMAIL_UPDATED = 'BOX_OFFICE_EMAIL_UPDATED';
}
