import {
    IconBrandBluesky,
    IconBrandDiscord,
    IconBrandFacebook,
    IconBrandFlickr,
    IconBrandGithub,
    IconBrandInstagram,
    IconBrandLinkedin,
    IconBrandPinterest,
    IconBrandReddit,
    IconBrandSnapchat,
    IconBrandTelegram,
    IconBrandTiktok,
    IconBrandTumblr,
    IconBrandTwitch,
    IconBrandVimeo,
    IconBrandVk,
    IconBrandWechat,
    IconBrandWeibo,
    IconBrandWhatsapp,
    IconBrandX,
    IconBrandYoutube,
} from '@tabler/icons-react';
import {t} from "@lingui/macro";

export const socialMediaConfig = {
    facebook: {name: () => t`Facebook`, icon: IconBrandFacebook, baseUrl: 'https://facebook.com/'},
    instagram: {name: () => t`Instagram`, icon: IconBrandInstagram, baseUrl: 'https://instagram.com/'},
    twitter: {name: () => t`X (Twitter)`, icon: IconBrandX, baseUrl: 'https://twitter.com/'},
    linkedin: {name: () => t`LinkedIn`, icon: IconBrandLinkedin, baseUrl: 'https://linkedin.com/company/'},
    discord: {name: () => t`Discord`, icon: IconBrandDiscord, baseUrl: 'https://discord.com/users/'},
    tiktok: {name: () => t`TikTok`, icon: IconBrandTiktok, baseUrl: 'https://tiktok.com/@'},
    bluesky: {name: () => t`Bluesky`, icon: IconBrandBluesky, baseUrl: 'https://bsky.app/profile/'},
    youtube: {name: () => t`YouTube`, icon: IconBrandYoutube, baseUrl: 'https://youtube.com/@'},
    snapchat: {name: () => t`Snapchat`, icon: IconBrandSnapchat, baseUrl: 'https://snapchat.com/add/'},
    twitch: {name: () => t`Twitch`, icon: IconBrandTwitch, baseUrl: 'https://twitch.tv/'},
    reddit: {name: () => t`Reddit`, icon: IconBrandReddit, baseUrl: 'https://reddit.com/u/'},
    pinterest: {name: () => t`Pinterest`, icon: IconBrandPinterest, baseUrl: 'https://pinterest.com/'},
    whatsapp: {name: () => t`WhatsApp`, icon: IconBrandWhatsapp, baseUrl: 'https://wa.me/'},
    telegram: {name: () => t`Telegram`, icon: IconBrandTelegram, baseUrl: 'https://t.me/'},
    vk: {name: () => t`VK`, icon: IconBrandVk, baseUrl: 'https://vk.com/'},
    weibo: {name: () => t`Weibo`, icon: IconBrandWeibo, baseUrl: 'https://weibo.com/'},
    wechat: {name: () => t`WeChat`, icon: IconBrandWechat, baseUrl: '#'},
    flickr: {name: () => t`Flickr`, icon: IconBrandFlickr, baseUrl: 'https://flickr.com/people/'},
    tumblr: {name: () => t`Tumblr`, icon: IconBrandTumblr, baseUrl: 'https://tumblr.com/blog/'},
    vimeo: {name: () => t`Vimeo`, icon: IconBrandVimeo, baseUrl: 'https://vimeo.com/'},
    github: {name: () => t`GitHub`, icon: IconBrandGithub, baseUrl: 'https://github.com/'},
};
